from typing import Protocol

from admirable.domain.entities.category import Category
from admirable.domain.value_objects.pagination import Page


class CategoryRepository(Protocol):
    async def get_by_id(self, category_id: int) -> Category | None: ...

    async def get_by_name(self, name: str) -> Category | None: ...

    async def list_paginated(self, page: int, per_page: int) -> Page[Category]: ...

    async def list_all(self) -> list[Category]: ...

    async def count(self) -> int: ...

    async def count_figures(self, category_id: int) -> int: ...

    async def add(self, category: Category) -> Category: ...

    async def update(self, category: Category) -> Category: ...

    async def delete(self, category_id: int) -> None: ...
