from typing import Protocol

from admirable.domain.entities.contact import Contact
from admirable.domain.value_objects.pagination import Page


class ContactRepository(Protocol):
    async def get_by_id(self, contact_id: int) -> Contact | None: ...

    async def list_paginated(self, page: int, per_page: int) -> Page[Contact]: ...

    async def list_active_ordered(self) -> list[Contact]: ...

    async def add(self, contact: Contact) -> Contact: ...

    async def update(self, contact: Contact) -> Contact: ...

    async def delete(self, contact_id: int) -> None: ...
