from typing import Protocol

from admirable.domain.entities.user import User


class UserRepository(Protocol):
    async def get_by_id(self, user_id: int) -> User | None: ...

    async def get_by_email(self, email: str) -> User | None: ...

    async def list_all_admins(self, page: int, per_page: int) -> list[User]: ...

    async def count_superadmins(self) -> int: ...

    async def add(self, user: User) -> User: ...

    async def update(self, user: User) -> User: ...

    async def delete(self, user_id: int) -> None: ...
